// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHttVFI4h4Sl8Xy0tJPDrW-YpcWAcqyLc',
    appId: '1:884628679060:web:78d8dce4e23a1ef19c0781',
    messagingSenderId: '884628679060',
    projectId: 'l-earn-8f2de',
    authDomain: 'l-earn-8f2de.firebaseapp.com',
    storageBucket: 'l-earn-8f2de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMFZcnIFmQIGbEAkAU7hwNXBX33MtJtg',
    appId: '1:884628679060:android:ccae00ca33cd7eb99c0781',
    messagingSenderId: '884628679060',
    projectId: 'l-earn-8f2de',
    storageBucket: 'l-earn-8f2de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLt18XbifeeX59AmPFsFAdg5Dv9lXnj8',
    appId: '1:884628679060:ios:63869eb7ea50e5489c0781',
    messagingSenderId: '884628679060',
    projectId: 'l-earn-8f2de',
    storageBucket: 'l-earn-8f2de.appspot.com',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLt18XbifeeX59AmPFsFAdg5Dv9lXnj8',
    appId: '1:884628679060:ios:63869eb7ea50e5489c0781',
    messagingSenderId: '884628679060',
    projectId: 'l-earn-8f2de',
    storageBucket: 'l-earn-8f2de.appspot.com',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHttVFI4h4Sl8Xy0tJPDrW-YpcWAcqyLc',
    appId: '1:884628679060:web:be53f4e58a84f62d9c0781',
    messagingSenderId: '884628679060',
    projectId: 'l-earn-8f2de',
    authDomain: 'l-earn-8f2de.firebaseapp.com',
    storageBucket: 'l-earn-8f2de.appspot.com',
  );
}
